# 이름
name: Github Actions

# 이벤트 트리거
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  My-deploy-job:
    runs-on: ubuntu-latest

    steps:
      - name: Hello world
        run : echo "Hello world"
